version: '3.8'

services:
  postgres_container_webant:
    image: postgres:15
    container_name: postgres_container_webant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_container_webant
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - homerep-network
#    restart: unless-stopped

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container_authtest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    ports:
#      - "8008:80"
#    networks:
#      - homerep-network
#    depends_on:
#      - postgres
#    restart: unless-stopped



networks:
  homerep-network:
    driver: bridge

volumes:
  postgres-data: