spring:
  application:
    name: HomeRepOAuth

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/homerep_auth
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql:  true
    hibernate:
      ddl-auto: create-drop
# properties:
#            hibernate:
#           format_sql: true

#sql:
#     init:
#   mode: always
#     schema-locations: "classpath:schema.sql"
#     data-locations: "classpath:data.sql"
logging:
  level:
    org:
      hibernate:
      SQL: debug
    type:
      descriptor:
        sql:
        BasicBinder: trace
#homerep:
#    app:
#        secret: 3yYVzp5nVElAYg123uRpOMq+fzQfFQ6OgoxTKuUz9Fg=
#        lifetime: 60000
server:
  port: 8082
homerep:
  secret: "yo78$$dontCrackPlease"
  lifetime: 30000

